export type RankingSource = {
  label: string;
  url: string;
};

export type HistoricalPerson = {
  rank: number;
  name: string;
  country: string;
  field: "宗教与思想" | "科学与技术" | "政治与制度" | "医学与生命" | "文化与艺术" | "探索与交流" | "经济与社会";
  era: "古代" | "中世纪" | "近世" | "近现代" | "现代";
  impact: string;
};

export type EasyProjectStatus = "已发币" | "持续关注" | "新收录";

export type EasyProject = {
  rank: number;
  name: string;
  direction: string;
  status?: EasyProjectStatus;
};

export type EasyProjectLinks = {
  website?: string;
  x?: string;
};

export type EasySeason = {
  season: number;
  period: string;
  location: string;
  demoDay: string;
  source: RankingSource;
  projects: readonly EasyProject[];
};

export const historyRankingSource: RankingSource = {
  label: "中文维基百科：影响人类历史进程的100名人排行榜",
  url: "https://zh.wikipedia.org/wiki/%E5%BD%B1%E5%93%8D%E4%BA%BA%E7%B1%BB%E5%8E%86%E5%8F%B2%E8%BF%9B%E7%A8%8B%E7%9A%84100%E5%90%8D%E4%BA%BA%E6%8E%92%E8%A1%8C%E6%A6%9C",
};

const historicalPeopleBase: readonly Omit<HistoricalPerson, "country">[] = [
  { rank: 1, name: "穆罕默德", field: "宗教与思想", era: "中世纪", impact: "创传伊斯兰教，并推动阿拉伯半岛形成统一政治共同体。" },
  { rank: 2, name: "艾萨克·牛顿", field: "科学与技术", era: "近世", impact: "以运动定律与万有引力奠定经典力学体系。" },
  { rank: 3, name: "耶稣", field: "宗教与思想", era: "古代", impact: "基督教的核心人物，其教义深刻影响全球文明。" },
  { rank: 4, name: "释迦牟尼", field: "宗教与思想", era: "古代", impact: "佛教创始人，形成跨越亚洲的思想与宗教传统。" },
  { rank: 5, name: "孔子", field: "宗教与思想", era: "古代", impact: "儒家思想奠基者，长期塑造东亚伦理、教育与治理。" },
  { rank: 6, name: "保禄", field: "宗教与思想", era: "古代", impact: "早期基督教领袖，推动基督教向非犹太世界传播。" },
  { rank: 7, name: "蔡伦", field: "科学与技术", era: "古代", impact: "改良造纸工艺，显著降低知识记录与传播成本。" },
  { rank: 8, name: "约翰内斯·谷登堡", field: "科学与技术", era: "中世纪", impact: "发展欧洲金属活字印刷，开启大规模出版时代。" },
  { rank: 9, name: "克里斯托弗·哥伦布", field: "探索与交流", era: "近世", impact: "其远航促成欧洲与美洲的持续接触。" },
  { rank: 10, name: "阿尔伯特·爱因斯坦", field: "科学与技术", era: "现代", impact: "相对论重塑现代物理学的时空与引力观念。" },
  { rank: 11, name: "路易·巴斯德", field: "医学与生命", era: "近现代", impact: "奠定微生物学与疫苗研究的重要基础。" },
  { rank: 12, name: "伽利略·伽利莱", field: "科学与技术", era: "近世", impact: "以实验和观测推动近代物理学与天文学。" },
  { rank: 13, name: "亚里士多德", field: "宗教与思想", era: "古代", impact: "建立跨哲学、逻辑与自然研究的系统知识框架。" },
  { rank: 14, name: "欧几里得", field: "科学与技术", era: "古代", impact: "《几何原本》奠定公理化几何的长期范式。" },
  { rank: 15, name: "摩西", field: "宗教与思想", era: "古代", impact: "犹太传统的重要先知与立法者。" },
  { rank: 16, name: "查尔斯·达尔文", field: "医学与生命", era: "近现代", impact: "自然选择理论奠定现代进化生物学。" },
  { rank: 17, name: "嬴政（秦始皇）", field: "政治与制度", era: "古代", impact: "建立中国首个中央集权统一帝国并推行制度标准化。" },
  { rank: 18, name: "盖乌斯·屋大维", field: "政治与制度", era: "古代", impact: "建立罗马元首制并开启帝国时代。" },
  { rank: 19, name: "尼古拉·哥白尼", field: "科学与技术", era: "近世", impact: "日心模型推动天文学变革与科学革命。" },
  { rank: 20, name: "安托万·拉瓦锡", field: "科学与技术", era: "近世", impact: "以定量实验和元素观念奠定近代化学。" },
  { rank: 21, name: "君士坦丁大帝", field: "政治与制度", era: "古代", impact: "承认基督教合法地位并推动罗马政治中心东移。" },
  { rank: 22, name: "詹姆斯·瓦特", field: "科学与技术", era: "近世", impact: "改良蒸汽机，提升工业革命的动力效率。" },
  { rank: 23, name: "迈克尔·法拉第", field: "科学与技术", era: "近现代", impact: "发现电磁感应，奠定发电与电动技术基础。" },
  { rank: 24, name: "詹姆斯·麦克斯韦", field: "科学与技术", era: "近现代", impact: "以方程组统一经典电、磁与光学理论。" },
  { rank: 25, name: "马丁·路德", field: "宗教与思想", era: "近世", impact: "宗教改革核心人物，推动新教形成。" },
  { rank: 26, name: "乔治·华盛顿", field: "政治与制度", era: "近世", impact: "领导美国独立并塑造早期共和制度。" },
  { rank: 27, name: "卡尔·马克思", field: "宗教与思想", era: "近现代", impact: "建立马克思主义理论，影响全球政治与社会运动。" },
  { rank: 28, name: "莱特兄弟", field: "科学与技术", era: "现代", impact: "完成可控动力飞行，开启现代航空时代。" },
  { rank: 29, name: "成吉思汗", field: "政治与制度", era: "中世纪", impact: "建立蒙古帝国并重塑欧亚政治与交流网络。" },
  { rank: 30, name: "亚当·斯密", field: "经济与社会", era: "近世", impact: "系统阐述分工与市场机制，奠定现代经济学。" },
  { rank: 31, name: "威廉·莎士比亚", field: "文化与艺术", era: "近世", impact: "其戏剧与诗歌深刻塑造英语文学和全球戏剧传统。" },
  { rank: 32, name: "约翰·道尔顿", field: "科学与技术", era: "近世", impact: "提出近代原子论并推进定量化学。" },
  { rank: 33, name: "亚历山大大帝", field: "政治与制度", era: "古代", impact: "其征服推动希腊化文化跨区域传播。" },
  { rank: 34, name: "拿破仑一世", field: "政治与制度", era: "近现代", impact: "以战争、法典和行政改革重塑欧洲制度。" },
  { rank: 35, name: "托马斯·爱迪生", field: "科学与技术", era: "近现代", impact: "推动电力、照明与工业化研发体系商业落地。" },
  { rank: 36, name: "安东尼·范·列文虎克", field: "医学与生命", era: "近世", impact: "以显微观察开拓微生物世界。" },
  { rank: 37, name: "威廉·莫顿", field: "医学与生命", era: "近现代", impact: "推动麻醉进入外科手术实践。" },
  { rank: 38, name: "古列尔莫·马可尼", field: "科学与技术", era: "现代", impact: "推进无线电通信技术的实用化。" },
  { rank: 39, name: "阿道夫·希特勒", field: "政治与制度", era: "现代", impact: "纳粹独裁与第二次世界大战造成全球性灾难。" },
  { rank: 40, name: "柏拉图", field: "宗教与思想", era: "古代", impact: "其哲学体系深刻影响西方政治与思想传统。" },
  { rank: 41, name: "奥利弗·克伦威尔", field: "政治与制度", era: "近世", impact: "英国内战与共和时期的重要军事政治领袖。" },
  { rank: 42, name: "亚历山大·格拉汉姆·贝尔", field: "科学与技术", era: "近现代", impact: "推动电话发明与现代电信产业形成。" },
  { rank: 43, name: "亚历山大·弗莱明", field: "医学与生命", era: "现代", impact: "发现青霉素，开启抗生素医疗时代。" },
  { rank: 44, name: "约翰·洛克", field: "宗教与思想", era: "近世", impact: "经验主义与自然权利思想影响现代自由主义。" },
  { rank: 45, name: "路德维希·范·贝多芬", field: "文化与艺术", era: "近现代", impact: "扩展交响与器乐表达，连接古典与浪漫主义。" },
  { rank: 46, name: "维尔纳·海森堡", field: "科学与技术", era: "现代", impact: "建立矩阵力学并提出不确定性原理。" },
  { rank: 47, name: "路易·达盖尔", field: "科学与技术", era: "近现代", impact: "推动摄影技术进入可复制的实用阶段。" },
  { rank: 48, name: "西蒙·玻利瓦尔", field: "政治与制度", era: "近现代", impact: "领导多个南美地区摆脱西班牙殖民统治。" },
  { rank: 49, name: "勒内·笛卡儿", field: "宗教与思想", era: "近世", impact: "开创近代西方哲学并发展解析几何。" },
  { rank: 50, name: "米开朗基罗", field: "文化与艺术", era: "近世", impact: "以雕塑、绘画与建筑代表文艺复兴艺术高峰。" },
  { rank: 51, name: "乌尔班二世", field: "宗教与思想", era: "中世纪", impact: "号召第一次十字军东征，改变地中海政治格局。" },
  { rank: 52, name: "欧麦尔·伊本·哈塔卜", field: "政治与制度", era: "中世纪", impact: "早期哈里发，推动伊斯兰国家快速扩张。" },
  { rank: 53, name: "阿育王", field: "政治与制度", era: "古代", impact: "统一印度大部并推动佛教广泛传播。" },
  { rank: 54, name: "圣奥古斯丁", field: "宗教与思想", era: "古代", impact: "其神学著作长期塑造西方基督教思想。" },
  { rank: 55, name: "威廉·哈维", field: "医学与生命", era: "近世", impact: "证实血液循环，奠定实验生理学。" },
  { rank: 56, name: "欧内斯特·卢瑟福", field: "科学与技术", era: "现代", impact: "揭示原子核结构并奠定核物理学。" },
  { rank: 57, name: "约翰·加尔文", field: "宗教与思想", era: "近世", impact: "建立改革宗神学体系并影响新教社会。" },
  { rank: 58, name: "格雷戈尔·孟德尔", field: "医学与生命", era: "近现代", impact: "发现遗传规律，奠定现代遗传学。" },
  { rank: 59, name: "马克斯·普朗克", field: "科学与技术", era: "现代", impact: "提出能量量子概念，开启量子物理。" },
  { rank: 60, name: "约瑟夫·李斯特", field: "医学与生命", era: "近现代", impact: "推广外科消毒法，显著降低手术感染。" },
  { rank: 61, name: "尼古拉斯·奥托", field: "科学与技术", era: "近现代", impact: "发展四冲程内燃机，为汽车工业提供基础动力。" },
  { rank: 62, name: "弗朗西斯科·皮萨罗", field: "探索与交流", era: "近世", impact: "征服印加帝国并推进西班牙在南美殖民。" },
  { rank: 63, name: "荷南·科尔蒂斯", field: "探索与交流", era: "近世", impact: "征服阿兹特克帝国并改变中美洲历史进程。" },
  { rank: 64, name: "托马斯·杰斐逊", field: "政治与制度", era: "近世", impact: "参与奠定美国共和制度并起草《独立宣言》。" },
  { rank: 65, name: "伊莎贝拉一世", field: "政治与制度", era: "近世", impact: "推动西班牙统一并资助跨大西洋航行。" },
  { rank: 66, name: "约瑟夫·斯大林", field: "政治与制度", era: "现代", impact: "推动苏联工业化，同时建立高压统治体系。" },
  { rank: 67, name: "尤利乌斯·凯撒", field: "政治与制度", era: "古代", impact: "其征服与政治改革加速罗马共和国向帝国转变。" },
  { rank: 68, name: "征服者威廉", field: "政治与制度", era: "中世纪", impact: "诺曼征服重塑英格兰政治、语言与土地制度。" },
  { rank: 69, name: "西格蒙德·弗洛伊德", field: "医学与生命", era: "现代", impact: "创立精神分析，改变心理与文化研究路径。" },
  { rank: 70, name: "爱德华·詹纳", field: "医学与生命", era: "近世", impact: "发展天花疫苗，开启现代免疫接种。" },
  { rank: 71, name: "威廉·伦琴", field: "科学与技术", era: "近现代", impact: "发现 X 射线，开启医学影像诊断。" },
  { rank: 72, name: "约翰·塞巴斯蒂安·巴赫", field: "文化与艺术", era: "近世", impact: "将巴洛克音乐的结构与复调艺术推向高峰。" },
  { rank: 73, name: "老子", field: "宗教与思想", era: "古代", impact: "道家思想的重要奠基者，《道德经》影响深远。" },
  { rank: 74, name: "伏尔泰", field: "宗教与思想", era: "近世", impact: "倡导理性、宽容与公民自由，推动启蒙思想。" },
  { rank: 75, name: "约翰内斯·开普勒", field: "科学与技术", era: "近世", impact: "行星运动定律奠定现代天文学的数学基础。" },
  { rank: 76, name: "恩里科·费米", field: "科学与技术", era: "现代", impact: "推动核物理与首个受控核链式反应。" },
  { rank: 77, name: "莱昂哈德·欧拉", field: "科学与技术", era: "近世", impact: "在分析、数论与力学等领域建立大量基础方法。" },
  { rank: 78, name: "让-雅克·卢梭", field: "宗教与思想", era: "近世", impact: "社会契约与教育思想影响现代政治哲学。" },
  { rank: 79, name: "尼科洛·马基雅维利", field: "宗教与思想", era: "近世", impact: "以现实主义方法重塑近代政治分析。" },
  { rank: 80, name: "托马斯·马尔萨斯", field: "经济与社会", era: "近世", impact: "人口与资源关系理论影响经济学与人口研究。" },
  { rank: 81, name: "约翰·肯尼迪", field: "政治与制度", era: "现代", impact: "在冷战危机管理与太空计划中产生重要影响。" },
  { rank: 82, name: "格雷戈里·平卡斯", field: "医学与生命", era: "现代", impact: "参与发明口服避孕药，改变生育与公共健康。" },
  { rank: 83, name: "摩尼", field: "宗教与思想", era: "古代", impact: "创立摩尼教并形成跨欧亚传播的宗教体系。" },
  { rank: 84, name: "弗拉基米尔·列宁", field: "政治与制度", era: "现代", impact: "领导十月革命并建立苏维埃政权。" },
  { rank: 85, name: "杨坚（隋文帝）", field: "政治与制度", era: "中世纪", impact: "完成中国再统一并建立影响后世的行政制度。" },
  { rank: 86, name: "瓦斯科·达伽马", field: "探索与交流", era: "近世", impact: "开辟欧洲绕非洲通往印度的海上航线。" },
  { rank: 87, name: "居鲁士二世", field: "政治与制度", era: "古代", impact: "建立阿契美尼德帝国并发展跨区域治理。" },
  { rank: 88, name: "彼得大帝", field: "政治与制度", era: "近世", impact: "以制度、军事与技术改革推动俄罗斯现代化。" },
  { rank: 89, name: "毛泽东", field: "政治与制度", era: "现代", impact: "领导中国革命并深刻塑造二十世纪中国政治。" },
  { rank: 90, name: "弗兰西斯·培根", field: "宗教与思想", era: "近世", impact: "倡导经验方法，对近代科学方法论影响深远。" },
  { rank: 91, name: "亨利·福特", field: "经济与社会", era: "现代", impact: "推广流水线量产，改变工业组织与大众消费。" },
  { rank: 92, name: "孟轲（孟子）", field: "宗教与思想", era: "古代", impact: "发展儒家伦理与政治学说，影响东亚思想。" },
  { rank: 93, name: "琐罗亚斯德", field: "宗教与思想", era: "古代", impact: "祆教传统创始人，对西亚宗教思想影响深远。" },
  { rank: 94, name: "伊丽莎白一世", field: "政治与制度", era: "近世", impact: "巩固英国宗教和解并推动海上力量扩张。" },
  { rank: 95, name: "米哈伊尔·戈尔巴乔夫", field: "政治与制度", era: "现代", impact: "其改革与外交政策推动冷战结束。" },
  { rank: 96, name: "美尼斯", field: "政治与制度", era: "古代", impact: "传统上被视为统一上下埃及和第一王朝的开创者。" },
  { rank: 97, name: "查理曼", field: "政治与制度", era: "中世纪", impact: "统一西欧大片地区并推动加洛林文艺复兴。" },
  { rank: 98, name: "荷马", field: "文化与艺术", era: "古代", impact: "《荷马史诗》奠定西方史诗与文学传统。" },
  { rank: 99, name: "查士丁尼一世", field: "政治与制度", era: "中世纪", impact: "主持编纂《民法大全》，影响后世大陆法。" },
  { rank: 100, name: "筏驮摩那", field: "宗教与思想", era: "古代", impact: "耆那教的重要奠基者与核心导师。" },
] as const;

/**
 * 人物所属地采用“当时的政治实体（现代常用地理对应）”口径。
 * 这不是对古代或跨国人物强行赋予现代国籍，而是方便读者检索和比较。
 */
export const historicalCountries = [
  "阿拉伯半岛（今沙特阿拉伯）",
  "英格兰（今英国）",
  "罗马帝国犹太行省（今以色列／巴勒斯坦）",
  "古印度（今尼泊尔／印度）",
  "鲁国（今中国）",
  "罗马帝国（今土耳其）",
  "东汉（今中国）",
  "神圣罗马帝国（今德国）",
  "热那亚共和国（今意大利）",
  "德国",
  "法国",
  "意大利",
  "古希腊（今希腊）",
  "古希腊（今希腊）",
  "古以色列",
  "英国",
  "秦朝（今中国）",
  "罗马帝国（今意大利）",
  "波兰王国（今波兰）",
  "法国",
  "罗马帝国（今塞尔维亚）",
  "苏格兰（今英国）",
  "英国",
  "苏格兰（今英国）",
  "神圣罗马帝国（今德国）",
  "美国",
  "普鲁士（今德国）",
  "美国",
  "蒙古帝国（今蒙古国）",
  "苏格兰（今英国）",
  "英格兰（今英国）",
  "英格兰（今英国）",
  "马其顿王国（今希腊／北马其顿）",
  "法国",
  "美国",
  "荷兰共和国（今荷兰）",
  "美国",
  "意大利",
  "德国",
  "古希腊（今希腊）",
  "英格兰（今英国）",
  "苏格兰（今英国）",
  "苏格兰（今英国）",
  "英格兰（今英国）",
  "德国",
  "德国",
  "法国",
  "委内瑞拉",
  "法国",
  "佛罗伦萨共和国（今意大利）",
  "法兰西王国（今法国）",
  "正统哈里发国（今沙特阿拉伯）",
  "孔雀王朝（今印度）",
  "罗马帝国（今阿尔及利亚）",
  "英格兰（今英国）",
  "新西兰／英国",
  "法国",
  "奥地利帝国（今捷克）",
  "德国",
  "英国",
  "德国",
  "西班牙",
  "西班牙",
  "美国",
  "卡斯蒂利亚王国（今西班牙）",
  "苏联（今格鲁吉亚）",
  "罗马共和国（今意大利）",
  "诺曼底公国（今法国）",
  "奥匈帝国（今捷克）",
  "英国",
  "德国",
  "神圣罗马帝国（今德国）",
  "周朝（今中国）",
  "法国",
  "神圣罗马帝国（今德国）",
  "意大利／美国",
  "瑞士",
  "日内瓦共和国（今瑞士）",
  "佛罗伦萨共和国（今意大利）",
  "英国",
  "美国",
  "美国",
  "萨珊波斯（今伊朗）",
  "俄罗斯帝国（今俄罗斯）",
  "隋朝（今中国）",
  "葡萄牙",
  "阿契美尼德帝国（今伊朗）",
  "俄罗斯帝国（今俄罗斯）",
  "中国",
  "英格兰（今英国）",
  "美国",
  "战国时期邹国（今中国）",
  "古波斯（今伊朗）",
  "英格兰（今英国）",
  "苏联（今俄罗斯）",
  "古埃及",
  "法兰克王国（今法国／德国）",
  "古希腊（今希腊）",
  "东罗马帝国（今土耳其）",
  "古印度（今印度）",
] as const;

export const historicalPeople: readonly HistoricalPerson[] = historicalPeopleBase.map((person, index) => ({
  ...person,
  country: historicalCountries[index] ?? "待考证",
}));

const easyOfficialSource: RankingSource = {
  label: "YZi Labs · EASY Residency 官方项目页",
  url: "https://www.yzilabs.com/easy-residency",
};

export const easySeasons: readonly EasySeason[] = [
  {
    season: 1,
    period: "2025.06 — 2025.08",
    location: "New York",
    demoDay: "New York Stock Exchange",
    source: easyOfficialSource,
    projects: [
      { rank: 1, name: "AMMO", direction: "社区 AI 助手 / Discord Agent" },
      { rank: 2, name: "APRO", direction: "AI 原生预言机", status: "已发币" },
      { rank: 3, name: "Bitway", direction: "比特币原生借贷 / Bitway Chain", status: "已发币" },
      { rank: 4, name: "Byte A.I.", direction: "加密支付外卖 Agent" },
      { rank: 5, name: "ComplyGen", direction: "AI 合规 / KYC" },
      { rank: 6, name: "Freebeat.AI", direction: "音乐驱动的视频生成 Agent" },
      { rank: 7, name: "Hubble AI", direction: "链上数据终端 / On-Chain Bloomberg" },
      { rank: 8, name: "Robata", direction: "机器人 / 具身智能去中心化数据网络" },
      { rank: 9, name: "Modus", direction: "Monad 上的链上主经纪商" },
      { rank: 10, name: "OptimAI", direction: "Web3 数据层 + AI 数字分身" },
      { rank: 11, name: "Paimon Finance", direction: "私募 / Pre-IPO 资产代币化" },
      { rank: 12, name: "Lumi", direction: "科研视觉 AI 副驾" },
      { rank: 13, name: "RecycleFarm", direction: "DePIN 碳信用 MRV" },
      { rank: 14, name: "StableStock", direction: "链上股票 / 稳定币买美股", status: "持续关注" },
      { rank: 15, name: "Video Tutor", direction: "AI 视频家教" },
    ],
  },
  {
    season: 2,
    period: "2025.10 — 2025.12",
    location: "Multi-city",
    demoDay: "Binance Blockchain Week Dubai",
    source: {
      label: "YZi Labs · Meet the EASY Residency Season 2 Cohort",
      url: "https://www.linkedin.com/pulse/meet-easy-residency-season-2-cohort-yzilabs-vvlif",
    },
    projects: [
      { rank: 1, name: "42.space", direction: "事件资产发行 / 把现实事件做成可交易代币", status: "持续关注" },
      { rank: 2, name: "Predict.fun", direction: "预测市场 / 资金可生息", status: "持续关注" },
      { rank: 3, name: "Bento.fun", direction: "社交化预测市场" },
      { rank: 4, name: "AllScale", direction: "自托管稳定币跨境企业银行" },
      { rank: 5, name: "Frontrun", direction: "专业交易员钱包" },
      { rank: 6, name: "Hertzflow", direction: "任意资产无许可杠杆市场", status: "持续关注" },
      { rank: 7, name: "Sats Terminal", direction: "比特币原生流动性协议" },
      { rank: 8, name: "Saturn Labs", direction: "比特币信用支撑的高收益稳定币", status: "持续关注" },
      { rank: 9, name: "Help.fun", direction: "非营利代币发行平台" },
      { rank: 10, name: "MeleeMon", direction: "稳定币对战手游" },
      { rank: 11, name: "4D Labs", direction: "空间智能大模型" },
      { rank: 12, name: "Manifolds", direction: "可控 3D 视频生成" },
      { rank: 13, name: "AgriDynamics", direction: "农业采摘机器人" },
      { rank: 14, name: "Trellis Robotics", direction: "软体机器人" },
      { rank: 15, name: "Advent", direction: "AI 精准基因治疗" },
      { rank: 16, name: "Neomera BioLab", direction: "非阿片类慢性病药物" },
      { rank: 17, name: "FingerDance", direction: "手语翻译 AI / 听障人群" },
    ],
  },
  {
    season: 3,
    period: "2026.02 — 2026.05",
    location: "New York + Bay Area",
    demoDay: "Computer History Museum",
    source: {
      label: "YZi Labs · Meet the EASY Residency Season 3 Cohort",
      url: "https://www.linkedin.com/pulse/meet-easy-residency-season-3-cohort-yzilabs-sez3c",
    },
    projects: [
      { rank: 1, name: "Bank of AI", direction: "BNB Chain 上 AI Agent 身份 / 支付层" },
      { rank: 2, name: "Brief Tech", direction: "诉讼证据自动整理" },
      { rank: 3, name: "Cournot", direction: "AI 概率输出可验证推理" },
      { rank: 4, name: "Dapital", direction: "社交信号 + 链上交易" },
      { rank: 5, name: "Flap", direction: "EVM 可编程发币基础设施", status: "持续关注" },
      { rank: 6, name: "GEMINT", direction: "收藏品 / IP 资产链上市场" },
      { rank: 7, name: "LayerV", direction: "链上期权与结构化产品" },
      { rank: 8, name: "LunarBase", direction: "CEX 级链上流动性 / Prop AMM" },
      { rank: 9, name: "L7", direction: "多市场资金账户 / Agent 资金接入" },
      { rank: 10, name: "Mobius", direction: "DeFi 统一保证金层" },
      { rank: 11, name: "Nemesis", direction: "无许可保证金交易" },
      { rank: 12, name: "Newsliquid", direction: "AI Agent 金融决策与执行" },
      { rank: 13, name: "Openstocks", direction: "代币化私募市场敞口" },
      { rank: 14, name: "PokerFi", direction: "扑克技巧游戏期权" },
      { rank: 15, name: "Polysights", direction: "预测市场经济自动化" },
      { rank: 16, name: "Renaiss", direction: "实物收藏品 RWA 流动性", status: "持续关注" },
      { rank: 17, name: "TermMax", direction: "固定利率、固定期限借贷", status: "已发币" },
      { rank: 18, name: "0xBow", direction: "合规导向隐私基础设施" },
      { rank: 19, name: "Functor", direction: "Agent 工作流自托管授权层" },
      { rank: 20, name: "Isaac", direction: "穆斯林市场无息稳定币新银行 / USD-i" },
      { rank: 21, name: "MARGIN X", direction: "BNB Chain 链上主经纪商" },
      { rank: 22, name: "Orbswap", direction: "多维 AMM 稳定币兑换" },
      { rank: 23, name: "SilentSwap", direction: "合规跨链隐私兑换" },
      { rank: 24, name: "Taco AI", direction: "AI Agent 加密交易执行层" },
      { rank: 25, name: "Vibe.fun", direction: "链上事件驱动衍生品" },
    ],
  },
  {
    season: 4,
    period: "2026 · 10 weeks",
    location: "Online + Bhutan",
    demoDay: "Bhutan",
    source: {
      label: "YZi Labs · Meet the EASY Residency Season 4 Cohort",
      url: "https://www.linkedin.com/pulse/meet-easy-residency-season-4-cohort-yzilabs-fswce",
    },
    projects: [
      { rank: 1, name: "Aile", direction: "区域稳定币链上外汇", status: "新收录" },
      { rank: 2, name: "Alloco", direction: "机构级链上 ETF / 策略产品" },
      { rank: 3, name: "D0", direction: "新兴市场本地支付入金" },
      { rank: 4, name: "De1", direction: "链上金融世界模型" },
      { rank: 5, name: "ElfomoFi", direction: "EVM Prop-AMM" },
      { rank: 6, name: "Facto", direction: "链上余额直接日常消费中间件" },
      { rank: 7, name: "FinTax", direction: "加密会计、税务、合规" },
      { rank: 8, name: "Kravata", direction: "拉美合规稳定币基础设施" },
      { rank: 9, name: "Liquorice", direction: "Intent / RFQ 做市库存信贷" },
      { rank: 10, name: "Meddcom AI", direction: "AI 预防健康与长寿" },
      { rank: 11, name: "Nara", direction: "跨境支付可编程信贷" },
      { rank: 12, name: "Neutral Trade", direction: "代币化对冲基金策略金库" },
      { rank: 13, name: "Nexroute", direction: "链上交易执行 / MEV" },
      { rank: 14, name: "Nxos", direction: "跨境贸易稳定币新银行" },
      { rank: 15, name: "Primus", direction: "机构链上隐私基础设施" },
      { rank: 16, name: "Roostoo", direction: "AI 交易代理训练与筛选" },
      { rank: 17, name: "SmartX", direction: "个性化链上社交交易" },
      { rank: 18, name: "Spectrum", direction: "加密到法币 24/7 清算" },
      { rank: 19, name: "Surgepay", direction: "印度侨民账单支付" },
      { rank: 20, name: "ViFi Labs", direction: "新兴市场货币链上 FX" },
      { rank: 21, name: "xAPI", direction: "AI Agent 的 API 市场" },
      { rank: 22, name: "XHunt", direction: "AI 创作者智能与变现" },
      { rank: 23, name: "XStable", direction: "链上黄金 / 外汇杠杆交易" },
      { rank: 24, name: "Zerodrift", direction: "企业软件智能体安全" },
    ],
  },
] as const;

/**
 * 只收录能由项目官网、项目官方社交页或 YZi Labs cohort 资料交叉确认的入口。
 * 未收录的项目会在页面明确显示“待核验”，避免把同名项目链接错配。
 */
export const easyProjectLinks: Readonly<Record<string, EasyProjectLinks>> = {
  "1:2": { website: "https://www.apro.com/", x: "https://x.com/APRO_Oracle" },
  "1:3": { website: "https://bitway.com/", x: "https://x.com/BitwayOfficial" },
  "1:6": { website: "https://freebeat.ai/" },
  "1:8": { website: "https://robata.net/" },
  "1:10": { website: "https://optimai.network/", x: "https://x.com/OptimaiNetwork" },
  "1:11": { website: "https://www.paimon.finance/", x: "https://x.com/Paimon_Finance" },
  "1:14": { website: "https://app.stablestock.finance/" },
  "2:1": { website: "https://www.42.space/" },
  "2:2": { website: "https://predict.fun/" },
  "2:3": { website: "https://bento.fun/", x: "https://x.com/Bentodotfun" },
  "2:4": { website: "https://www.allscale.io/", x: "https://x.com/allscaleio" },
  "2:5": { x: "https://x.com/frontrunpro" },
  "2:6": { x: "https://x.com/Hertzflow_xyz" },
  "2:8": { x: "https://x.com/usdat21" },
  "2:9": { website: "https://help.fun/" },
  "2:10": { website: "https://www.meleemon.com/" },
  "3:5": { website: "https://flap.sh/", x: "https://x.com/flapdotsh" },
  "3:8": { website: "https://lunarbase.gg/", x: "https://x.com/LunarBaseX" },
  "3:15": { website: "https://www.polysights.xyz/", x: "https://x.com/Polysights" },
  "3:16": { website: "https://www.renaiss.xyz/", x: "https://x.com/renaissxyz" },
  "3:17": { website: "https://termmax.ts.finance/", x: "https://x.com/TermMaxFi" },
  "3:18": { website: "https://0xbow.io/" },
  "3:22": { website: "https://orbswap.org/", x: "https://x.com/0xorbSwap" },
  "3:23": { website: "https://www.silentswap.com/", x: "https://x.com/SilentSwap" },
  "3:25": { website: "https://www.vibe.fun/" },
  "4:8": { website: "https://kravata.co/" },
  "4:9": { website: "https://liquorice.tech/" },
  "4:12": { website: "https://www.neutral.trade/", x: "https://x.com/TradeNeutral" },
  "4:15": { website: "https://primuslabs.xyz/", x: "https://x.com/primus_labs" },
  "4:16": { website: "https://www.roostoo.com/" },
  "4:21": { website: "https://www.xapi.to/", x: "https://x.com/xapi_to" },
  "4:22": { website: "https://xhunt.ai/" },
  "4:23": { website: "https://www.xstable.ai/" },
};

export function getEasyProjectLinks(season: number, rank: number): EasyProjectLinks {
  return easyProjectLinks[`${season}:${rank}`] ?? {};
}

export const totalEasyProjects = easySeasons.reduce((total, season) => total + season.projects.length, 0);
